Web server whit Express
lvzh90/notes-app pull request #1
Opened 2021-09-24 05:30 UTC by lvzh90

2021-09-25 02:14 UTC, gh0stl1m commented on web-server/package.json
> +  "description": "",
We should always try to add a description that summarize what is the purpose of the service/project.

2021-09-25 02:14 UTC, gh0stl1m commented on web-server/package.json
> +  "author": "",
What do you think if we put here your name and email following the next structure
```suggestion
  "author": "Linda Zapata <lvzh90@gmail.com>",
```

2021-09-25 02:14 UTC, gh0stl1m commented on web-server/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
We should try to remove all the dead code since we don't have any tests yet, we should try to remove this line.
```suggestion
```

2021-09-25 02:14 UTC, gh0stl1m commented on web-server/src/app.js
> +})
We should try to avoid this because route configurations should be placed on their own folder, so what we can do is to basically create another folder called routes and inside this folder, we can create a router based on the domain. For instance:
```
-- src
--- routes
---- index.js
---- router.js
---- help
----- handlers.js
----- endpoints.js
----- index.js
```

2021-09-27 18:03 UTC, lvzh90 commented on web-server/src/app.js
> +})
Done!

2021-09-27 18:20 UTC, lvzh90 commented on web-server/package.json
> +  "description": "",
Done!

2021-09-28 02:20 UTC, gh0stl1m requested changes

2021-09-28 02:20 UTC, gh0stl1m commented on web-server/src/utils/forecast.js
> +    request({url, json: true}, (error, { body }) => {
@lvzh90 why don't we use `promises` or `async-await` here instead of using callbacks?

2021-09-28 21:53 UTC, lvzh90 commented on web-server/src/routers/index.js
> +router.get('', (req, res) => {
Yes, this is the root router.
Done

2021-09-28 23:52 UTC, lvzh90 commented on web-server/src/utils/forecast.js
> +    const url = 'http://api.weatherstack.com/current?access_key=c59a2f758b6643ef821c65d80bc29e21&'
Done!

2021-09-29 05:01 UTC, lvzh90 commented on web-server/src/utils/forecast.js
> +    request({url, json: true}, (error, { body }) => {
Done!

2021-09-29 05:01 UTC, lvzh90 commented on web-server/src/utils/forecast.js
> +const forescat = (latitude, longitude, callback) => {
Done!

2021-09-29 05:01 UTC, lvzh90 commented on web-server/src/utils/geocode.js
> +const geocode = (address, callback) => {
Done!

2021-09-29 05:02 UTC, lvzh90 commented on web-server/src/utils/geocode.js
> +    })
Done!

2021-09-29 05:02 UTC, lvzh90 commented on web-server/public/js/app.js
> +weatherForm.addEventListener('submit', (event) => {
Done!

2021-09-29 05:03 UTC, lvzh90 commented on web-server/public/js/app.js
> +    })
Done!

2021-09-29 05:18 UTC, lvzh90 commented on web-server/public/js/app.js
> +    const url = 'http://localhost:3000/weather?address=' + location;
We are using vanilla and this implementation it not supported

2021-09-29 05:20 UTC, gh0stl1m approved these changes
LGTM ❤️💙

2021-09-29 05:24 UTC, merged